package model

import "time"

//
// This struct is not used right now but could be useful in the future
// if we want to show more detailed commits in a list displayed with the heatmap
//

type Commit struct {
	//field   type      JSON
	Id        int       `json:"id"`           // generated by db
	UserId    int       `json:"userId"`       // refering to Users table
	commitId  string    `json:"commitId"`     // commit id reported by git
	date      time.Time `json:"date"`         // date commit was logged
	changes   int       `json:"filesChanged"` // number of files changed in this commit
	additions int       `json:"additions"`    // number of code additions reported by git commit
	deletions int       `json:"deletions"`    // number of code deletions reported by git commit
}
